openapi: "3.0.0"
info:
  title: Test
  version: DEV-SNAPSHOT
  description: OpenAPI Specification

paths:
  /public/path/path1/create:
    get:
      operationId: GetCallWithoutParametersAndResponse
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                  type: string
