name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Node in Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          ref: ${{ github.event.release.target_commitish }}
      - name: Validate and extract release information
        id: release
        uses: manovotny/github-releases-for-automated-package-publishing-action@v1.0.0
        with:
          draft: false
      - name: Install yarn
        run: npm install --global yarn
      - name: Install packages
        run: yarn install
      - name: Build library
        run: yarn run release
      - name: Run unit tests
        run: yarn run test:coverage
      - name: Run e2e tests
        run: yarn run test:e2e
      - name: Submit to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV }}
      - name: Publish tagged version
        if: steps.release.outputs.tag != ''
        run: yarn publish --new-version ${{ steps.release.outputs.version }} --tag ${{ steps.release.outputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish version
        if: steps.release.outputs.tag == ''
        run: yarn publish --new-version ${{ steps.release.outputs.version }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
#       - name: Publish
#         id: publish
#         if: github.ref == 'refs/heads/master'
#         uses: JS-DevTools/npm-publish@v1
#         with:
#           token: ${{ secrets.NPM_AUTH_TOKEN }}
#           check-version: true
#           access: public
#       - if: steps.Publish.outputs.type != 'none'
#         run: |
#           echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
#   test-windows:
#     name: Node in Windows
#     runs-on: windows-latest
#     steps:
#       - name: Checkout source
#         uses: actions/checkout@v2
#       - name: Install node
#         uses: actions/setup-node@v1
#         with:
#           node-version: '14'
#       - name: Install yarn
#         run: npm install --global yarn
#       - name: Install packages
#         run: yarn install
#       - name: Build library
#         run: yarn run release
#       - name: Run unit tests
#         run: yarn run test:coverage
#       - name: Run e2e tests
#         run: sudo yarn run test:e2e
#       - name: Submit to Codecov
#         run: yarn run codecov
