name: CI

on: [ push, pull_request ]

jobs:
  test-ubuntu:
    name: Node in Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
      - name: Install yarn
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Build library
        run: sudo yarn run release
      - name: Run unit tests
        run: sudo yarn run test:coverage
      - name: Run e2e tests
        run: sudo yarn run test:e2e
      - name: Submit to Codecov
        run: sudo yarn run codecov
  test-windows:
    name: Node in Windows
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
      - name: Install yarn
        run: npm install --global yarn
      - name: Install rollup
        run: npm install -g rollup
      - name: Build library
        run: yarn run release
      - name: Run unit tests
        run: yarn run test:coverage
      - name: Run e2e tests
        run: sudo yarn run test:e2e
      - name: Submit to Codecov
        run: yarn run codecov
