name: CI

on:
  push:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Node in Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '14.20.1'
          always-auth: true
      - name: Install packages
        run: npm install
      - name: Build library
        run: npm run release
      - name: Run unit tests
        run: npm run test:coverage
      - name: Run e2e tests
        run: npm run test:e2e
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: ./coverage